parameters:

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          bigint: PlayOrPay\Infrastructure\Storage\Doctrine\Type\BigIntType
          role_enum: PlayOrPay\Infrastructure\Storage\Doctrine\Type\RoleEnumType
          steam_id: PlayOrPay\Infrastructure\Storage\Doctrine\Type\Steam\SteamIdType
          event_picker_type: PlayOrPay\Infrastructure\Storage\Doctrine\Type\EventPickerType
          event_pick_type: PlayOrPay\Infrastructure\Storage\Doctrine\Type\EventPickType
          event_pick_played_status: PlayOrPay\Infrastructure\Storage\Doctrine\Type\EventPickPlayedStatusType
          game_store_id: PlayOrPay\Infrastructure\Storage\Doctrine\Type\Game\StoreIdType
          reward_reason: PlayOrPay\Infrastructure\Storage\Doctrine\Type\Event\RewardReasonType
          event_comment_game_reference_type: \PlayOrPay\Infrastructure\Storage\Doctrine\Type\Event\EventCommentGameReferenceType
          event_pick_status: PlayOrPay\Infrastructure\Storage\Doctrine\Type\Event\EventPickStatusType
        mapping_types:
          uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/domain'
                prefix: 'PlayOrPay\Domain'
                alias: Domain
            LeaguePeriod:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/league'
                prefix: 'League\Period'
        dql:
            string_functions:
                DATE: DoctrineExtensions\Query\Mysql\Date
