version: '3'

services:
  caddy:
    volumes:
      - ./etc/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

  php:
    volumes:
      - ./etc/php/php.ini:/etc/php7/conf.d/90-php.ini:ro
      - ./etc/php/php-fpm.conf:/etc/php7/php-fpm.conf:ro
      - ./etc/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      #- ./etc/php/crontab:/etc/crontabs/root:ro
      # doesn't work because it's mounted as 1000:users and crond ignores it
    ports:
      - "2323:22"
